language: android
jdk: oraclejdk8
sudo: false
os:
  - linux
android:
  components:
    - tools
    - build-tools-25.0.0
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-android-support
    - android-16
    - android-23
    - android-25
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-22
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'